os: osx
before_install:
  - brew update
install:
  - npm install -q
script:
  - npm run lint # disable testing until we have test cases
after_script:
  - chmod a+xr ./scripts/*
  - ls -al ./scripts/
  - ./scripts/build_project.sh
  - ./scripts/gh_pages_deploy.sh